name = "berda-server"
main = "cloud/worker.js"
compatibility_date = "2026-09-17"

[vars]
OWNER_LOGIN = "owner"

[[d1_databases]]
binding = "DB"
database_name = "berda-db"
database_id = "abbdeae7-797a-46ce-b331-0457c06928ae"